_buildenv_lib_include buildenv/debug.sh

function _buildenv_append_environment() {
  _buildenv_is_active || return 1
  local _env=$(_buildenv_environment_path _load.sh)
  if [ ! -f "$_env" ];then
    mkdir -p `dirname "$_env"`
    echo "# Autogenerated by $0" > $_env
  fi
  echo "$@" >> $_env
}

function _buildenv_remove_environment() {
  _buildenv_debug "_buildenv_remove_environment not yet implemented"
}
